### PR TITLE
Update module initiate travis 

### PR DESCRIPTION
**Pull request by milestorme**

### CODE REVIEW

**Comment by milestorme** [comment]
looks like I fixed https://travis-ci.org/milestorme/mod-cfbg/jobs/574127730 / https://github.com/azerothcore/mod-cfbg/issues/3 with this pr

**Comment by milestorme** [comment]
confirmation again of issue https://github.com/azerothcore/mod-cfbg/issues/3 in the complete travis build for this pr


Using configuration file /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using ACE version: 6.3.3
AzerothCore rev. cde07f89b9be 2019-08-18 12:25:24 +0200 (master branch) (Unix, Release) (worldserver-daemon)
<Ctrl-C> to stop.

Opening DatabasePool 'world_adzal'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
DatabasePool 'world_adzal' opened successfully. 2 total connections running.
Opening DatabasePool 'characters_adzal'. Asynchronous connections: 1, synchronous connections: 2.
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
DatabasePool 'characters_adzal' opened successfully. 3 total connections running.
Opening DatabasePool 'auth_adzal'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
MySQL client library: 5.7.27
MySQL server ver: 5.7.25-0ubuntu0.16.04.2 
DatabasePool 'auth_adzal' opened successfully. 2 total connections running.
Realm running as realm ID 1
Using World DB: ACDB 335.3 (dev)
Initializing Scripts...
Loading C++ scripts

Module config: Invalid or missing configuration file : /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!

Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/data/
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1

Loading Trinity strings...
>> Loaded 1167 trinity strings in 2 ms

**Comment by ghost** [comment]
Travis configuration seems ok, but could someone please explain the issue with the CFBG config? Travis has no custom configuration file, so the error message is ok (it's the same for e.g. the beastmaster module).

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by milestorme** [comment]
Yeah I get that error message on live core too , on .reload conf it spews the error again in console it’s not reading the conf . @Stoabrogga

**Pull request merged**
