### PR TITLE
BG Queue Spam Announce

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
@merdlin

https://github.com/azerothcore/azerothcore-wotlk/issues/2714

### CODE REVIEW

**Comment by DevMatheuss** [comment]
I'm compiling to test ...

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi @Helias can you guys tell us why travis failed? it says clang-7 not found wtf


@merdlin so?

**Comment by disclosurez** [comment]
testing

**Comment by disclosurez** [comment]
this breaks WSG, no flags are placed.
Also this does not fix the spam, see attached.

lol

**Comment by IntelligentQuantum** [comment]
Add this to your core for flags https://github.com/azerothcore/azerothcore-wotlk/commit/b868f0ad04e78b180c721cf6b1c3820c513573e3

**Comment by disclosurez** [comment]
this works please merge

**Comment by Nefertumm** [comment]
Merged. Ty everyone :)

**Comment by BarbzYHOOL** [comment]
@IntelligentQuantum thank you for the fix!!

@disclosurez ty for testing!!

and @merdlin not thank you leecher

**Pull request merged**
