### PR TITLE
fix(GroupInvite): correct add to bg if player has group

### LINKED ISSUE #12: Join as a Group doesn't work [$100]
Joining as a group (party) does not work.

It would be nice if it can work and somehow try (but of course cannot guarantee) to maintain the original group members within the same team.

EDIT: there is a bounty on this issue. To consider it fixed, it MUST be properly tested and ALL corner cases should work. Including all different configurations enabled, for example:

```
CFBG.BalancedTeams = 1
CFBG.Include.Avg.Ilvl.Enable = 1
CFBG.Players.Count.In.Group = 2
CFBG.EvenTeams.Enabled = 1
CFBG.EvenTeams.MaxPlayersThreshold = 5
```

<bountysource-plugin>

---
There is a **[$100 open bounty](https://www.bountysource.com/issues/91199193-join-as-a-group-doesn-t-work?utm_campaign=plugin&utm_content=tracker%2F146727645&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146727645&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
Close #12

### CODE REVIEW

**Comment by Nano-GG** [comment]
Im testing this right now, but im not sure why some ppl are unattackable.

**Comment by Winfidonarleyan** [comment]
@n4ndo Pr is WIP, no need test now

**Comment by mnclaras** [comment]
Can this be used on a real server or it has bugs?

**Comment by Winfidonarleyan** [comment]
> Can this be used on a real server or it has bugs?

Yes, can

**Comment by lyo3d** [comment]
Me sale este error: https://ibb.co/jGB9Mgz
Core: AzerothCore Ultima Actualización

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-cfbg/pull/97

**Pull request closed without merging**
